import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-h-full bg-blue-900 text-white' style={{ height: '100vh' }}>
        <h1 >Hello world</h1>
        <Link href='/signup'>Get started</Link>
      </main>
    </>
  )
}
